### ISSUE TITLE
IncompleteFieldsMatch isIn() and isNotIn() signatures

### ISSUE THREAD

**Issue by Firtzberg** [ipavlic/apex-fp#14]
Looking at the [documentation](https://www.apexfp.org/api/function/IncompleteFieldsMatch#isin) it says

> Defines a set membership condition for the current field. value has to be a Set<T>, where T is a Boolean, Date, Datetime, Decimal, Double, Id, Integer, Long or String. Other types are not supported and will throw an exception.

I see in the implementation you just do
```
public FieldsMatch isIn(Object value) {
    return filterWith(BinaryRelation.IS_IN, value);
}
```
You can overload the definition with other signatures to constraint the type at compile time by replacing it with
```
public FieldsMatch isIn(Set<Boolean> value) {
    return filterWith(BinaryRelation.IS_IN, value);
}
public FieldsMatch isIn(Set<Date> value) {
    return filterWith(BinaryRelation.IS_IN, value);
}
//...
```
Same for `isNotIn()`.
Is there a syntax problems which prevents you from doing this?

**Comment by ipavlic** [comment]
I see a couple of questions:

1. Why is the `Set` type not constrained at compile time in `IncompleteFieldsMatch`?
2. Can you pass a `Set<String>` to a method that takes a `Set<Object>`
3. Why is a `Set<Object>` not currently allowed?
4. Can we support `Set<SObject>`?

Let's try to tackle them in order.

## 1

`IncompleteFieldsMatch` is just an intermediary step to build a `FieldMatchCondition` for the `FieldsMatch`. Field value is dynamically obtained, so it is an `Object`. We also have to store the other value. We could store it as an `Object` again or we could have a reference for every supported type in `FieldsMatchCondition`.

If we store references for all supported types, we also have to be able to find which one stores a value when we are comparing, and be careful to differentiate between null because a reference is not defined, and null, because it is a null reference.

So we chose `Object` as the simpler solution. This spilled over to `IncompleteFieldsMatch`, which again takes an object. There's an opportunity to overload here as well, and we would get `M*T` methods (M methods, T supported types). Even if we overload, some comparisons still don't make sense and won't be caught at compile time; for example we define a `String` field from an `SObject` (like `Opportunity.Description`) and want it to be `lessThan` 5. We can overload `lessThan` to take all supported types (`String`, `Long`, `Integer`, ...), but it won't understand at compile time that this comparison does not make sense, because we don't know the type of a chosen `SObject` field at compile time. So we chose `Object` as a simpler solution.

There's some benefit in only overloading `Set` methods like `isIn` and `notIn`, for sure, but I feel it's inconsistent.

## 2

No. Try it.

## 3

It's not that it's not _allowed_, it's not _supported_. I didn't see much benefit in expressions like `field(Opportunity.Description).isIn(new Set<Object>{'Foo', 5, new Opportunity()})`. Which I think brings us to point 4.

## 4

We could support sets of `SObject`. The tricky part is that instances obtained from the database will have additional data (like `Id`s), and an equality comparison performed by the `Set.contains` will likely not work as one might expect it to work. It warrants additional investigation though.

**Comment by Firtzberg** [comment]
Hvala Ilija for the detailed response. Great analysis of my questions, btw.

## 1

My proposal is related to `isIn` and `isNotIn`, I had no intention to modify other methods, like `lessThan`.
As you said `Set<String>` cannot be passed to a method that takes a `Set<Object>`, I see now that for consistency it makes sense to go with an object.

I thought it's better to enforce stronger types to have a pit of success, rather than relying on people reading a warning in the documentation. I can imagine people passing lists into the function instead of sets.
As an alternative, you could change the [error message](https://github.com/ipavlic/apex-fp/blob/master/sfdx-source/apex-fp/main/classes/function/FieldsMatch.cls#L140) in the thrown exception to say it should be a primitive set, like `Set<String>`.

## 2

I wasn't 100% sure

## 3

OK

## 4

Fair enough

**Comment by ipavlic** [comment]
Re point 1, I am suggesting either a) making everything compile time checked or b) leaving everything unchecked. If all `IncompleteFieldsMatch` public methods are overloaded for all supported types, then we would have additional level of type safety.

Example:
1. `IncompleteFieldsMatch.lessThan` takes an `Object` and constructs a `FieldMatchCondition`
2. `FieldsMatch.call` checks `FieldMatchCondition` with `FieldsMatch.conditionSatisfied`, which then uses `FieldsMatch.contains` or `PrimitiveComparer.compare`
3. `FieldsMatch.contains` or `PrimitiveComparer.compare` can throw an error

We could:
1. Overload `FieldsMatch.lessThan` for every supported data type, and everything else remains the same.

We get additional safety as we can refuse unsupported types at compile time. We are still not fully safe, as the field itself cannot be checked at compile time.

There are about 10 methods, and some additional aliases. We currently support 10 primitive types, so we would have 100+ overloads in total.
